Listas vs Arrays

In [1]:
import numpy as np # Importa la librería numpy con el alias np

In [2]:
my_list=[1,2,3,4] # Define una lista de Python

In [3]:
arr=np.array(my_list) # Convierte la lista de Python a un array de NumPy

In [4]:
arr # Muestra el array

array([1, 2, 3, 4])

In [5]:
print(arr) # Imprime el array

[1 2 3 4]


In [6]:
lista=[1,2,3,'Hola Mundo'] # Define una lista de Python con diferentes tipos de datos

In [7]:
(lista[3]) # Accede al cuarto elemento de la lista (índice 3)

'Hola Mundo'

In [8]:
matriz=[[1,2,3],
        [4,5,6],
        [7,8,9]] # Define una lista anidada que representa una matriz

In [9]:
matriz[2] # Accede a la tercera fila de la matriz (índice 2)

[7, 8, 9]

In [10]:
matriz[2][1] # Accede al segundo elemento (índice 1) de la tercera fila (índice 2)

8

In [11]:
import numpy as np # Importa la librería numpy (ya importada anteriormente, pero se puede incluir de nuevo por claridad en esta sección)

In [12]:
numero=[3,4,46] # Define una lista de Python
a=np.array(numero) # Convierte la lista a un array de NumPy
a[0:2] # Accede a los elementos del array desde el índice 0 hasta antes del índice 2

array([3, 4])

In [13]:
numero # Muestra la lista original

[3, 4, 46]

In [14]:
print(a[0:2]) # Imprime los elementos del array desde el índice 0 hasta antes del índice 2

[3 4]


In [15]:
type(a) # Verifica el tipo de dato de la variable 'a' (debería ser un ndarray de NumPy)

numpy.ndarray

In [16]:
b=np.array(lista) # Convierte la lista 'lista' (que contiene diferentes tipos de datos) a un array de NumPy
print(b) # Imprime el array resultante. Observa cómo NumPy intenta encontrar un tipo de dato común (en este caso, cadenas)

['1' '2' '3' 'Hola Mundo']


In [17]:
type(b) # Verifica el tipo de dato de la variable 'b'

numpy.ndarray

In [18]:
lista=[2,4,6] # Define una nueva lista de Python

In [19]:
c=np.array(lista) # Convierte la nueva lista a un array de NumPy

In [20]:
c*4 # Multiplica cada elemento del array 'c' por 4 (broadcasting)

array([ 8, 16, 24])

In [21]:
secuencia=np.arange(25) # Crea un array de NumPy con una secuencia de números del 0 al 24

In [22]:
secuencia # Muestra el array 'secuencia'

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
print(secuencia) # Imprime el array 'secuencia'

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [24]:
impares=np.arange(1,24,2) # Crea un array de NumPy con números impares desde 1 hasta antes de 24

In [25]:
impares # Muestra el array 'impares'

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [26]:
secuencia=np.linspace(3,8,10) # Crea un array de NumPy con 10 números espaciados uniformemente entre 3 y 8

In [27]:
secuencia # Muestra el array 'secuencia'

array([3.        , 3.55555556, 4.11111111, 4.66666667, 5.22222222,
       5.77777778, 6.33333333, 6.88888889, 7.44444444, 8.        ])

In [28]:
ceros=np.zeros((4,4),dtype=int) # Crea un array de NumPy de 4x4 lleno de ceros con tipo de dato entero

In [29]:
ceros # Muestra el array 'ceros'

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [30]:
cincos=np.full((3,3),5) # Crea un array de NumPy de 3x3 lleno de cincos

In [31]:
ceros.shape # Muestra la forma (dimensiones) del array 'ceros'

(4, 4)

In [32]:
cincos # Muestra el array 'cincos'

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [33]:
cincos**5 # Eleva cada elemento del array 'cincos' a la potencia de 5

array([[3125, 3125, 3125],
       [3125, 3125, 3125],
       [3125, 3125, 3125]])

In [34]:
arr1=np.full((5,4) ,3) # Crea un array de NumPy de 5x4 lleno de tres

In [35]:
arr1=np.full(shape=(5,4),fill_value=4.42) # Crea un array de NumPy de 5x4 lleno de 4.42

In [36]:
arr1 # Muestra el array 'arr1'

array([[4.42, 4.42, 4.42, 4.42],
       [4.42, 4.42, 4.42, 4.42],
       [4.42, 4.42, 4.42, 4.42],
       [4.42, 4.42, 4.42, 4.42],
       [4.42, 4.42, 4.42, 4.42]])

In [37]:
arr1 # Muestra el array 'arr1' (después de ser reasignado en la celda anterior)

array([[4.42, 4.42, 4.42, 4.42],
       [4.42, 4.42, 4.42, 4.42],
       [4.42, 4.42, 4.42, 4.42],
       [4.42, 4.42, 4.42, 4.42],
       [4.42, 4.42, 4.42, 4.42]])

In [38]:
azar=np.random.rand(4,3) # Crea un array de NumPy de 4x3 con números aleatorios entre 0 y 1

In [39]:
azar # Muestra el array 'azar'

array([[0.40195771, 0.50846819, 0.2772512 ],
       [0.06133288, 0.77074463, 0.08914653],
       [0.3865438 , 0.48759704, 0.08937584],
       [0.08318629, 0.63261135, 0.13017441]])

In [40]:
print(azar) # Imprime el array 'azar' con números aleatorios entre 0 y 1

[[0.40195771 0.50846819 0.2772512 ]
 [0.06133288 0.77074463 0.08914653]
 [0.3865438  0.48759704 0.08937584]
 [0.08318629 0.63261135 0.13017441]]


In [41]:
azar=np.random.randint(1,19,(4,5)) # Crea un array de NumPy de 4x5 con números enteros aleatorios entre 1 (inclusive) y 19 (exclusive)

In [42]:
azar.shape # Muestra la forma (dimensiones) del array 'azar'

(4, 5)

In [43]:
azar2=azar.reshape(2,10) # Remodela el array 'azar' a una forma de 2 filas y 10 columnas

In [44]:
azar2 # Muestra el array 'azar2' remodelado

array([[ 9, 13,  1, 17,  3,  5,  1, 13,  5, 13],
       [ 7, 13,  7,  6, 17,  3,  7,  1, 11, 15]], dtype=int32)

In [45]:
azar # Muestra el array 'azar' original (la operación reshape crea una vista, no modifica el original por defecto)

array([[ 9, 13,  1, 17,  3],
       [ 5,  1, 13,  5, 13],
       [ 7, 13,  7,  6, 17],
       [ 3,  7,  1, 11, 15]], dtype=int32)

In [46]:
azar[1,2] # Accede al elemento en la fila con índice 1 y columna con índice 2 del array 'azar'

np.int32(13)

In [47]:
azar[:,2] # Accede a todos los elementos de la columna con índice 2 del array 'azar'

array([ 1, 13,  7,  1], dtype=int32)

In [48]:
mascara= azar>10 # Crea un array booleano (máscara) donde los elementos son True si el valor correspondiente en 'azar' es mayor que 10, y False en caso contrario

In [49]:
azar[mascara] # Usa la máscara booleana para seleccionar y mostrar solo los elementos de 'azar' que son mayores que 10

array([13, 17, 13, 13, 13, 17, 11, 15], dtype=int32)

In [50]:
mascara

array([[False,  True, False,  True, False],
       [False, False,  True, False,  True],
       [False,  True, False, False,  True],
       [False, False, False,  True,  True]])

In [51]:
# Esta celda está vacía. Podrías usarla para probar alguna otra operación con el array 'azar' o la máscara 'mascara'.

In [52]:
print(azar[mascara]) # Imprime los elementos de 'azar' que cumplen la condición de la máscara (ser mayores que 10)

[13 17 13 13 13 17 11 15]
